name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Install AWS CLI
      run: |
        pip install --upgrade pip
        pip install awscli --upgrade --user

    - name: Create S3 bucket
      run: |
        aws s3 mb s3://grisisobiana1234
      
    - name: Upload code to S3
      run: |
        aws s3 cp deploy.zip s3://grisisobiana1234/deploy.zip

    - name: Pull code to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application \
          --application-name my-application
        aws elasticbeanstalk create-application-version \
          --application-name my-application \
          --version-label v1.0.0 \
          --source-bundle S3Bucket="grisisobiana1234",S3Key="deploy.zip"
        aws elasticbeanstalk update-environment \
          --environment-name my-environment \
          --version-label v1.0.0


